### ISSUE TITLE
ASP core console signing problem

### ISSUE THREAD

**Issue by Astimus** [brutaldev/StrongNameSigner#41]
Console signing doesn't work with asp .core applications.
There are diffrenet errors in console:
"Warning: Format of the executable (.exe) or library (.dll) is invalid"
"Error: Operation is not valid due to the current state of the object"

**Comment by brutaldev** [comment]
The tool does not officially support signing .NET Core assemblies. PR is welcome if anyone wants to add this support.

**Comment by carlescs** [comment]
The thing is that  using the GUI tool to sign them and adding them as reference works. It does not work using the nuget package. Just my two cents...

**Comment by ffMathy** [comment]
I really need this as well.

Currently just trying to sign a .NET Framework project that references a .NET Standard 1.6 class library, which I think is a very valid use case scenario.

It could seem as if this could be resolved by just updating `Mono.Cecil` @brutaldev?

**Comment by brutaldev** [comment]
@ffMathy There is a branch for the latest version of `[mono-cecil](https://deventerprise.uservoice.com/forums/198724-general/suggestions/3914087-linux-support-using-mono)`, however, they have internal file locking issues which make the unit tests fail as well as large signing batches not being able to complete.

**Comment by paul-kiar** [comment]
I'm getting this error on .Net Framework assemblies, it signs successfully but then outputs errors

`Operation is not valid due to the current state of the object.
    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
    at Brutal.Dev.StrongNameSigner.SigningHelper.GetAssemblyInfo(String assemblyPath, String[] probingPaths)
    at Brutal.Dev.StrongNameSigner.AutomaticBuildTask.Execute()`

**Comment by brutaldev** [comment]
@paul-kiar Update the the latest version.

**Comment by paul-kiar** [comment]
@brutaldev I'm using 2.1.4, the latest package on nuget, including the prereleases.

**Comment by paul-kiar** [comment]
The libraries I attempting to sign are 4.5.2 and 4.6.1

**Comment by paul-kiar** [comment]
Specifically IdentityModel.OidcClient version 2.6.0 from nuget.

**Comment by paul-kiar** [comment]
Turns out it's the project settings that were changed causing the error, I removed the project changes from my project and the errors stop.  I then used console app and a pre-build event to sign the libraries.  My project is being built in VS 2017 15.7.2 and the project target dotnet framework is 4.7.1.

**Comment by paul-kiar** [comment]
This is the code I removed from the project:
`  <Import Project="..\..\..\packages\Brutal.Dev.StrongNameSigner.2.1.4\build\Brutal.Dev.StrongNameSigner.targets" Condition="Exists('..\..\..\packages\Brutal.Dev.StrongNameSigner.2.1.4\build\Brutal.Dev.StrongNameSigner.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\..\packages\Brutal.Dev.StrongNameSigner.2.1.4\build\Brutal.Dev.StrongNameSigner.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\..\packages\Brutal.Dev.StrongNameSigner.2.1.4\build\Brutal.Dev.StrongNameSigner.targets'))" />
  </Target>`
