### ISSUE TITLE
Error when signing assembly; Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by alphaleonis** [brutaldev/StrongNameSigner#47]
Running `StrongNameSigner.Console.exe -a net452\IdentityModel.dll` gives the following error:
`Error: Operation is not valid due to the current state of the object.`.

The IdentityModel.dll is from the IdentityModel nuget package version 3.9.0, and StrongNameSigner is downloaded from NuGet version 2.1.4.

**Comment by Comprion-OJapes** [comment]
Hi!

I ran into the same problem last year and together with @brutaldev we found that the existence of a pdb file causes this problem. Right now I'm again facing that problem, using the NuGet-Package of ZXing.Net (https://www.nuget.org/packages/ZXing.Net/) with version 0.15.0

As a workaround: delete all .pdb-files in the packages-subfolder.

I hope that this will give a clue on what causes the problem so that it can be hopefully fixed in the future.

**Comment by alphaleonis** [comment]
That's a good tip... unfortunately I can't seem to be able to sign the **IdentityModel** NuGet package even if I remove the .pdb-file. :(

**Comment by alphaleonis** [comment]
I still get the following exception trace:

````
error : Operation is not valid due to the current state of the object.
 error :    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
 error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
 error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
 error :    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
 error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
 error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
 error :    at Brutal.Dev.StrongNameSigner.SigningHelper.GetAssemblyInfo(String assemblyPath, String[] probingPaths)
 error :    at Brutal.Dev.StrongNameSigner.AutomaticBuildTask.Execute()
````

**Comment by alphaleonis** [comment]
Sorry, my bad. It actually does seem to work from the console app at least when removing the .pdb file as suggested.

**Comment by alphaleonis** [comment]
Actually it seems this problem was "fixed" in the master branch already, but never released. See commit 237726afe2ee6427f2999674021d480bfea48e5f

**Comment by brutaldev** [comment]
@alphaleonis The last release was 7 months ago (v2.1.4) which contains that fix (tagged for 2.1.4 as well) which was made almost a year ago now. The automatic build task is in the same assembly as the signing helper where the change was made so it's definitely included.

**Comment by alphaleonis** [comment]
Yeah, sorry about that. I mixed everything up here with different versions of things, building them and trying to fix the problem. It was all very confusing, and still is a bit.

It seems that I got the error if the `Mono.Cecil.Mdb.dll` and `Mono.Cecil.Pdb.dll` files were present in the same directory as the .exe, otherwise I didn't.  

After updating to the latest version of Cecil though, it seems to work as it should, *except* that now it seems that it is not possible to write the output to the same destination as the input file, since that produces an Access Denied error because "the file is used by another process".  

I will investigate a little further and let you know what I find out. Sorry for all my confusing ramblings, it's been one of those days.

**Comment by alphaleonis** [comment]
I did some quick tests, and I can't see any file locking if I dispose the `AssemblyDefinition` returned by `AssemblyDefinition.ReadAssembly`.  They must be disposed before writing to the file that was read. This means you probably have to write a temporary file first, then dispose the `AssemblyDefinition` and then move the temporary file to the actual file if in-place-signing is desired. 

I tried implementing a quick-fix for this in the `SignAssembly` method, and all unit tests passed except for one using `FixAssemblyReferences` since I didn't implement it in this method. (I cache `AssemblyInfo? instances instead of `AssemblyDefinition` in these cases).

This is with the latest version of Mono.Cecil from NuGet, and everything seems to work.

If you'd like I could probably spend a bit more time and create a proper implementation and submit a PR.

**Comment by brutaldev** [comment]
Sure, a PR would be great for this. Do it on the mono.cecil-0.10 branch but just upgrade to whatever the latest is in NuGet. I'll give it a quick run now myself to see if I can get the tests to pass using your suggestions.

**Comment by alphaleonis** [comment]
Nice. Thanks. I just noted though that you don't delete the temp-files afterwards which we should probably do to be nice to the user.   Also all the calls to  `File.SetAttributes`, aren't they supposed to operate on the actual target file rather than the temporary file so that the actual target file can be overwritten by the copy? (The temp file we just created so it seems unlikely that would be read-only)?

I might be missing something, kind of tired here, just some reflections I thought I'd point them out. :) Thanks for a quick fix anyway! Guess you won't be needing my PR. :)

**Comment by brutaldev** [comment]
Setting the file attributes is to force the read-only flag off, could get away without doing it on the temp file but it's done to ensure the file it replaces will always have the read-only flag off. There was a long issue about how this also caused issues that appeared as file locks but I'm not prepared to go down that rabbit whole again or introduce any other issues by removing it right now.

I can add the code to delete the temp files later (unless you want to review and PR), I don't really want to do anything else on this project right now so I was just getting it working and moving onto other work.

**Comment by alphaleonis** [comment]
I understand completely. Thanks for the quick fix attempt, unfortunately this caused a couple of other problems when .pdb files were present it seems (`Error: Symbols were found but are not matching the assembly`).  I will investigate and submit a PR once I'm done, and try to get some new tests that cover this scenario as well.

**Comment by brutaldev** [comment]
@alphaleonis That would be awesome, I never had the chance to really test everything with the new libs. I added the temp file deletes to `master` last night as well. Any other fixes you want to make will be much appreciated.
